#Latihan Pandas

In [ ]:
#P1
import pandas as pd
import numpy as np

data = pd.Series([2, 4, 6, 8, 10])
print(data)

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
#P2

data = pd.Series(['a','b','c']) #!sS
np1 = np.array(['x','y','z'])
data_np = pd.Series(np1)

print(data)
print(data_np)

#mengatur indeks pada numpy array data-np di atas

data_np = pd.Series(np1, index=[2,3,4])
print(data_np)

0    a
1    b
2    c
dtype: object
0    x
1    y
2    z
dtype: object
2    x
3    y
4    z
dtype: object

In [ ]:
#P3

ds1 = pd.Series([2, 4, 6, 8, 10])
ds2 = pd.Series([1, 3, 5, 7, 9])
dsa = ds1 + ds2
dsb = ds1 - ds2
dsc = ds1 * ds2
dsd = ds1 / ds2

print(dsa)
print(dsb)
print(dsc)
print(dsd)

0     3
1     7
2    11
3    15
4    19
dtype: int64
0    1
1    1
2    1
3    1
4    1
dtype: int64
0     2
1    12
2    30
3    56
4    90
dtype: int64
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.111111
dtype: float64

In [ ]:
#P4

ds = pd.Series([2, 4, 6, 8, 10])

print("Pandas Series dan type")
print(ds)
print(type(ds))
print("Konver Pandas Series ke Python list")
print(ds.tolist())
print(type(ds.tolist()))

Pandas Series dan type
0     2
1     4
2     6
3     8
4    10
dtype: int64
<class 'pandas.core.series.Series'>
Konver Pandas Series ke Python list
[2, 4, 6, 8, 10]
<class 'list'>

In [ ]:
#P5

np_array = np.array([0, 20, 30, 40, 50])

print("NumPy array:")
print(np_array)


new_np = pd.Series(np_array)

print("konversi Pandas series:")
print(new_np)

NumPy array:
[ 0 20 30 40 50]
konversi Pandas series:
0     0
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
# P6 https://numpy.org/doc/1.16/reference/generated/ numpy.random.RandomState.html

num_state = np.random.RandomState(100)
num_series = pd.Series(num_state.normal(10, 4, 20))

print(num_series)
print(num_state)

0      3.000938
1     11.370722
2     14.612143
3      8.990256
4     13.925283
5     12.056875
6     10.884719
7      5.719827
8      9.242017
9     11.020006
10     8.167892
11    11.740654
12     7.665620
13    13.267388
14    12.690883
15     9.582355
16     7.874878
17    14.118931
18     8.247458
19     5.526727
dtype: float64
RandomState(MT19937)

In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Alam-A99/Pandas_Latih/main/penjualan.csv')
df

df.head(2)

   nama  jan  feb  mar  apr
0  Andi  100  135   85   75
1  Budi  200  240  185  160

In [ ]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/Alam-A99/DATAAKSI/main/dataset_fiskal_97_hipoFull.csv')
df

df.head(5)

,Kota,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
0,Kota Banda Aceh,2014,77.91,49.42,26.00,96.98,47.59,83.94,72.02,153.66,...,175.78,253.43,286.18,100.88,133.54,5.31,9.79,0.47,65.31,2.82
1,Kota Banda Aceh,2015,54.88,37.29,35.35,112.77,59.88,74.74,52.84,119.84,...,98.47,285.13,133.72,268.34,254.48,10.50,6.19,0.46,64.99,7.33
2,Kota Banda Aceh,2016,78.91,27.08,39.83,107.56,52.78,96.58,97.41,179.24,...,264.70,212.19,192.71,64.94,59.59,9.57,3.68,0.44,71.00,4.82
3,Kota Banda Aceh,2017,72.77,26.01,46.46,109.93,80.91,63.84,73.98,150.55,...,219.24,288.64,277.40,272.15,267.70,7.77,9.79,0.46,83.49,7.27
4,Kota Banda Aceh,2018,93.06,82.81,31.70,127.89,60.87,77.19,80.88,148.09,...,259.48,87.86,51.55,132.27,178.19,17.43,5.50,0.36,73.57,5.52

In [ ]:
# df.info()
# df.describe()
# df.tail()
#df.rank()
kota_sorong = df["Kota"] == "Kota Sorong"
kota_sorong_data = df[kota_sorong]
kota_sorong_data.head(10)

,Kota,Tahun,DBH_PAJAK,DBH_SDA,DBH_Lainnya,DAU_Grant,DAU_Earmark,DAK_Fisik,DAK_Nonfisik,PAD,...,bm_lingkungan,bm_ekonomi,bm_infrastruktur,bm_pariwisata,bm_perlindungan_sosial,KEMISKINAN,PENGANGGURAN,KETIMPANGAN,IPM,PE
1056,Kota Sorong,2014,80.42,30.98,27.92,133.21,75.47,61.35,91.06,215.07,...,162.93,63.74,153.42,106.30,55.63,10.93,7.37,0.49,80.79,6.43
1057,Kota Sorong,2015,98.24,35.51,42.75,128.86,65.65,80.64,63.95,192.12,...,138.68,194.64,237.54,114.27,161.03,11.84,6.72,0.33,63.49,4.38
1058,Kota Sorong,2016,118.89,35.71,38.50,171.87,64.22,112.36,91.30,168.70,...,150.18,70.64,223.35,169.86,245.34,9.65,5.08,0.36,82.12,3.58
1059,Kota Sorong,2017,107.24,83.42,40.37,168.15,93.78,114.48,84.09,211.07,...,78.79,88.63,297.66,141.82,220.01,18.23,5.82,0.31,72.90,4.25
1060,Kota Sorong,2018,104.94,91.06,46.62,154.77,103.84,69.25,78.67,240.86,...,270.82,159.89,119.47,278.45,208.79,15.05,3.09,0.34,77.07,4.99
1061,Kota Sorong,2019,131.97,56.82,69.26,183.12,121.69,114.53,80.53,281.63,...,153.71,177.62,174.55,142.07,277.39,6.84,4.78,0.46,75.46,4.06
1062,Kota Sorong,2020,116.28,67.28,73.72,156.21,142.40,94.42,141.83,174.79,...,146.82,114.70,132.38,143.36,54.51,13.70,9.22,0.39,78.66,3.45
1063,Kota Sorong,2021,138.49,113.67,57.69,173.31,83.56,99.41,91.17,248.49,...,214.92,129.11,160.15,145.88,189.26,7.77,3.27,0.31,80.79,4.39
1064,Kota Sorong,2022,105.81,108.63,41.69,232.20,125.93,92.21,130.82,274.78,...,160.51,71.74,264.24,259.16,246.84,11.44,9.03,0.33,66.97,2.12
1065,Kota Sorong,2023,80.40,49.05,63.66,137.98,94.78,101.75,126.07,265.28,...,212.06,125.80,221.05,212.70,185.33,16.30,9.80,0.46,84.08,6.63